// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpaceShip.proto

package com.example.springprotobuf.api;

public final class SpacShipProtos {
  private SpacShipProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SpaceShipOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.springprotobuf.api.SpaceShip)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string model = 1;</code>
     * @return The model.
     */
    java.lang.String getModel();
    /**
     * <code>string model = 1;</code>
     * @return The bytes for model.
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <code>string captain = 2;</code>
     * @return The captain.
     */
    java.lang.String getCaptain();
    /**
     * <code>string captain = 2;</code>
     * @return The bytes for captain.
     */
    com.google.protobuf.ByteString
        getCaptainBytes();

    /**
     * <code>int32 fuel = 3;</code>
     * @return The fuel.
     */
    int getFuel();

    /**
     * <code>.com.example.springprotobuf.api.SpaceShip.CargoType cargo = 4;</code>
     * @return The enum numeric value on the wire for cargo.
     */
    int getCargoValue();
    /**
     * <code>.com.example.springprotobuf.api.SpaceShip.CargoType cargo = 4;</code>
     * @return The cargo.
     */
    com.example.springprotobuf.api.SpacShipProtos.SpaceShip.CargoType getCargo();
  }
  /**
   * Protobuf type {@code com.example.springprotobuf.api.SpaceShip}
   */
  public static final class SpaceShip extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.springprotobuf.api.SpaceShip)
      SpaceShipOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SpaceShip.newBuilder() to construct.
    private SpaceShip(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SpaceShip() {
      model_ = "";
      captain_ = "";
      cargo_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SpaceShip();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SpaceShip(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              model_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              captain_ = s;
              break;
            }
            case 24: {

              fuel_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              cargo_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.springprotobuf.api.SpacShipProtos.internal_static_com_example_springprotobuf_api_SpaceShip_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.springprotobuf.api.SpacShipProtos.internal_static_com_example_springprotobuf_api_SpaceShip_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.springprotobuf.api.SpacShipProtos.SpaceShip.class, com.example.springprotobuf.api.SpacShipProtos.SpaceShip.Builder.class);
    }

    /**
     * Protobuf enum {@code com.example.springprotobuf.api.SpaceShip.CargoType}
     */
    public enum CargoType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FRUIT = 0;</code>
       */
      FRUIT(0),
      /**
       * <code>WEAPONS = 1;</code>
       */
      WEAPONS(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FRUIT = 0;</code>
       */
      public static final int FRUIT_VALUE = 0;
      /**
       * <code>WEAPONS = 1;</code>
       */
      public static final int WEAPONS_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CargoType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static CargoType forNumber(int value) {
        switch (value) {
          case 0: return FRUIT;
          case 1: return WEAPONS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CargoType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CargoType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CargoType>() {
              public CargoType findValueByNumber(int number) {
                return CargoType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.example.springprotobuf.api.SpacShipProtos.SpaceShip.getDescriptor().getEnumTypes().get(0);
      }

      private static final CargoType[] VALUES = values();

      public static CargoType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CargoType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.example.springprotobuf.api.SpaceShip.CargoType)
    }

    public static final int MODEL_FIELD_NUMBER = 1;
    private volatile java.lang.Object model_;
    /**
     * <code>string model = 1;</code>
     * @return The model.
     */
    @java.lang.Override
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      }
    }
    /**
     * <code>string model = 1;</code>
     * @return The bytes for model.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAPTAIN_FIELD_NUMBER = 2;
    private volatile java.lang.Object captain_;
    /**
     * <code>string captain = 2;</code>
     * @return The captain.
     */
    @java.lang.Override
    public java.lang.String getCaptain() {
      java.lang.Object ref = captain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        captain_ = s;
        return s;
      }
    }
    /**
     * <code>string captain = 2;</code>
     * @return The bytes for captain.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCaptainBytes() {
      java.lang.Object ref = captain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        captain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUEL_FIELD_NUMBER = 3;
    private int fuel_;
    /**
     * <code>int32 fuel = 3;</code>
     * @return The fuel.
     */
    @java.lang.Override
    public int getFuel() {
      return fuel_;
    }

    public static final int CARGO_FIELD_NUMBER = 4;
    private int cargo_;
    /**
     * <code>.com.example.springprotobuf.api.SpaceShip.CargoType cargo = 4;</code>
     * @return The enum numeric value on the wire for cargo.
     */
    @java.lang.Override public int getCargoValue() {
      return cargo_;
    }
    /**
     * <code>.com.example.springprotobuf.api.SpaceShip.CargoType cargo = 4;</code>
     * @return The cargo.
     */
    @java.lang.Override public com.example.springprotobuf.api.SpacShipProtos.SpaceShip.CargoType getCargo() {
      @SuppressWarnings("deprecation")
      com.example.springprotobuf.api.SpacShipProtos.SpaceShip.CargoType result = com.example.springprotobuf.api.SpacShipProtos.SpaceShip.CargoType.valueOf(cargo_);
      return result == null ? com.example.springprotobuf.api.SpacShipProtos.SpaceShip.CargoType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getModelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, model_);
      }
      if (!getCaptainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, captain_);
      }
      if (fuel_ != 0) {
        output.writeInt32(3, fuel_);
      }
      if (cargo_ != com.example.springprotobuf.api.SpacShipProtos.SpaceShip.CargoType.FRUIT.getNumber()) {
        output.writeEnum(4, cargo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getModelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, model_);
      }
      if (!getCaptainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, captain_);
      }
      if (fuel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, fuel_);
      }
      if (cargo_ != com.example.springprotobuf.api.SpacShipProtos.SpaceShip.CargoType.FRUIT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, cargo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.springprotobuf.api.SpacShipProtos.SpaceShip)) {
        return super.equals(obj);
      }
      com.example.springprotobuf.api.SpacShipProtos.SpaceShip other = (com.example.springprotobuf.api.SpacShipProtos.SpaceShip) obj;

      if (!getModel()
          .equals(other.getModel())) return false;
      if (!getCaptain()
          .equals(other.getCaptain())) return false;
      if (getFuel()
          != other.getFuel()) return false;
      if (cargo_ != other.cargo_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
      hash = (37 * hash) + CAPTAIN_FIELD_NUMBER;
      hash = (53 * hash) + getCaptain().hashCode();
      hash = (37 * hash) + FUEL_FIELD_NUMBER;
      hash = (53 * hash) + getFuel();
      hash = (37 * hash) + CARGO_FIELD_NUMBER;
      hash = (53 * hash) + cargo_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.springprotobuf.api.SpacShipProtos.SpaceShip parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springprotobuf.api.SpacShipProtos.SpaceShip parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springprotobuf.api.SpacShipProtos.SpaceShip parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springprotobuf.api.SpacShipProtos.SpaceShip parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springprotobuf.api.SpacShipProtos.SpaceShip parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springprotobuf.api.SpacShipProtos.SpaceShip parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springprotobuf.api.SpacShipProtos.SpaceShip parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.springprotobuf.api.SpacShipProtos.SpaceShip parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.springprotobuf.api.SpacShipProtos.SpaceShip parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.springprotobuf.api.SpacShipProtos.SpaceShip parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.springprotobuf.api.SpacShipProtos.SpaceShip parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.springprotobuf.api.SpacShipProtos.SpaceShip parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.springprotobuf.api.SpacShipProtos.SpaceShip prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.springprotobuf.api.SpaceShip}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.springprotobuf.api.SpaceShip)
        com.example.springprotobuf.api.SpacShipProtos.SpaceShipOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.springprotobuf.api.SpacShipProtos.internal_static_com_example_springprotobuf_api_SpaceShip_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.springprotobuf.api.SpacShipProtos.internal_static_com_example_springprotobuf_api_SpaceShip_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.springprotobuf.api.SpacShipProtos.SpaceShip.class, com.example.springprotobuf.api.SpacShipProtos.SpaceShip.Builder.class);
      }

      // Construct using com.example.springprotobuf.api.SpacShipProtos.SpaceShip.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        model_ = "";

        captain_ = "";

        fuel_ = 0;

        cargo_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.springprotobuf.api.SpacShipProtos.internal_static_com_example_springprotobuf_api_SpaceShip_descriptor;
      }

      @java.lang.Override
      public com.example.springprotobuf.api.SpacShipProtos.SpaceShip getDefaultInstanceForType() {
        return com.example.springprotobuf.api.SpacShipProtos.SpaceShip.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.springprotobuf.api.SpacShipProtos.SpaceShip build() {
        com.example.springprotobuf.api.SpacShipProtos.SpaceShip result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.springprotobuf.api.SpacShipProtos.SpaceShip buildPartial() {
        com.example.springprotobuf.api.SpacShipProtos.SpaceShip result = new com.example.springprotobuf.api.SpacShipProtos.SpaceShip(this);
        result.model_ = model_;
        result.captain_ = captain_;
        result.fuel_ = fuel_;
        result.cargo_ = cargo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.springprotobuf.api.SpacShipProtos.SpaceShip) {
          return mergeFrom((com.example.springprotobuf.api.SpacShipProtos.SpaceShip)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.springprotobuf.api.SpacShipProtos.SpaceShip other) {
        if (other == com.example.springprotobuf.api.SpacShipProtos.SpaceShip.getDefaultInstance()) return this;
        if (!other.getModel().isEmpty()) {
          model_ = other.model_;
          onChanged();
        }
        if (!other.getCaptain().isEmpty()) {
          captain_ = other.captain_;
          onChanged();
        }
        if (other.getFuel() != 0) {
          setFuel(other.getFuel());
        }
        if (other.cargo_ != 0) {
          setCargoValue(other.getCargoValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.springprotobuf.api.SpacShipProtos.SpaceShip parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.springprotobuf.api.SpacShipProtos.SpaceShip) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object model_ = "";
      /**
       * <code>string model = 1;</code>
       * @return The model.
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          model_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string model = 1;</code>
       * @return The bytes for model.
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string model = 1;</code>
       * @param value The model to set.
       * @return This builder for chaining.
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string model = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearModel() {
        
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }
      /**
       * <code>string model = 1;</code>
       * @param value The bytes for model to set.
       * @return This builder for chaining.
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        model_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object captain_ = "";
      /**
       * <code>string captain = 2;</code>
       * @return The captain.
       */
      public java.lang.String getCaptain() {
        java.lang.Object ref = captain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          captain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string captain = 2;</code>
       * @return The bytes for captain.
       */
      public com.google.protobuf.ByteString
          getCaptainBytes() {
        java.lang.Object ref = captain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          captain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string captain = 2;</code>
       * @param value The captain to set.
       * @return This builder for chaining.
       */
      public Builder setCaptain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        captain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string captain = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCaptain() {
        
        captain_ = getDefaultInstance().getCaptain();
        onChanged();
        return this;
      }
      /**
       * <code>string captain = 2;</code>
       * @param value The bytes for captain to set.
       * @return This builder for chaining.
       */
      public Builder setCaptainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        captain_ = value;
        onChanged();
        return this;
      }

      private int fuel_ ;
      /**
       * <code>int32 fuel = 3;</code>
       * @return The fuel.
       */
      @java.lang.Override
      public int getFuel() {
        return fuel_;
      }
      /**
       * <code>int32 fuel = 3;</code>
       * @param value The fuel to set.
       * @return This builder for chaining.
       */
      public Builder setFuel(int value) {
        
        fuel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 fuel = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFuel() {
        
        fuel_ = 0;
        onChanged();
        return this;
      }

      private int cargo_ = 0;
      /**
       * <code>.com.example.springprotobuf.api.SpaceShip.CargoType cargo = 4;</code>
       * @return The enum numeric value on the wire for cargo.
       */
      @java.lang.Override public int getCargoValue() {
        return cargo_;
      }
      /**
       * <code>.com.example.springprotobuf.api.SpaceShip.CargoType cargo = 4;</code>
       * @param value The enum numeric value on the wire for cargo to set.
       * @return This builder for chaining.
       */
      public Builder setCargoValue(int value) {
        
        cargo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.example.springprotobuf.api.SpaceShip.CargoType cargo = 4;</code>
       * @return The cargo.
       */
      @java.lang.Override
      public com.example.springprotobuf.api.SpacShipProtos.SpaceShip.CargoType getCargo() {
        @SuppressWarnings("deprecation")
        com.example.springprotobuf.api.SpacShipProtos.SpaceShip.CargoType result = com.example.springprotobuf.api.SpacShipProtos.SpaceShip.CargoType.valueOf(cargo_);
        return result == null ? com.example.springprotobuf.api.SpacShipProtos.SpaceShip.CargoType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.example.springprotobuf.api.SpaceShip.CargoType cargo = 4;</code>
       * @param value The cargo to set.
       * @return This builder for chaining.
       */
      public Builder setCargo(com.example.springprotobuf.api.SpacShipProtos.SpaceShip.CargoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cargo_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.example.springprotobuf.api.SpaceShip.CargoType cargo = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCargo() {
        
        cargo_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.springprotobuf.api.SpaceShip)
    }

    // @@protoc_insertion_point(class_scope:com.example.springprotobuf.api.SpaceShip)
    private static final com.example.springprotobuf.api.SpacShipProtos.SpaceShip DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.springprotobuf.api.SpacShipProtos.SpaceShip();
    }

    public static com.example.springprotobuf.api.SpacShipProtos.SpaceShip getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SpaceShip>
        PARSER = new com.google.protobuf.AbstractParser<SpaceShip>() {
      @java.lang.Override
      public SpaceShip parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpaceShip(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SpaceShip> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SpaceShip> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.springprotobuf.api.SpacShipProtos.SpaceShip getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_springprotobuf_api_SpaceShip_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_springprotobuf_api_SpaceShip_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SpaceShip.proto\022\036com.example.springpro" +
      "tobuf.api\"\242\001\n\tSpaceShip\022\r\n\005model\030\001 \001(\t\022\017" +
      "\n\007captain\030\002 \001(\t\022\014\n\004fuel\030\003 \001(\005\022B\n\005cargo\030\004" +
      " \001(\01623.com.example.springprotobuf.api.Sp" +
      "aceShip.CargoType\"#\n\tCargoType\022\t\n\005FRUIT\020" +
      "\000\022\013\n\007WEAPONS\020\001B0\n\036com.example.springprot" +
      "obuf.apiB\016SpacShipProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_springprotobuf_api_SpaceShip_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_springprotobuf_api_SpaceShip_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_springprotobuf_api_SpaceShip_descriptor,
        new java.lang.String[] { "Model", "Captain", "Fuel", "Cargo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
